[default]

[[directives]]
name = "simple resize"
urlpattern = "/convert/w/([0-9]+)/h/([0-9]+)/(.+)"
of = "png"
engine = "imaging"
[directives.values]
"$dw" = "$1"
"$dh" = "$2"
"$filepath" = "$3"
[directives.src]
type = "fs"
root = "/tmp"
path = "$filepath"
[[directives.converts]]
function = "resize"
parameters = {dw = "$dw", dh = "$dh"}
