[default]

[[directives]]
name = "simple resize"
urlpattern = "/convert/e/([a-z]+)/w/([0-9]+)/h/([0-9]+)/(.+)"
of = "png"
engine = "$engine"
[directives.vars]
"$engine" = "$1"
"$dw" = "$2"
"$dh" = "$3"
"$filepath" = "$4"
[directives.src]
type = "fs"
root = "./tmp"
path = "$filepath"
[[directives.converts]]
type = "resize"
parameters = {dw = "$dw", dh = "$dh"}

