[default]
  [default.src]
  type = "fs"
  mount = "./"

[[directives]]
name = "simple resize"
urlpattern = "/convert/{:dw}/{:dh}/*"
of = "png"
engine = "imaging"
  [[directives.converts]]
  function = "resize"
  parameters = {dw = ":dw", dh = ":dh"}
